//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_3_entitiy_task.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string gender { get; set; }
        public string profession { get; set; }
        public string studentID { get; set; }
        public string email { get; set; }
        public System.DateTime dob { get; set; }
    }
}
